change Dockerfile & conf

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -73,14 +73,12 @@ jobs:
           key: ${{ secrets.VPS_SSH_KEY }}
           script: |
             set -e
-
-            if [ ! -d "/root/Friendify/.git" ]; then
-              rm -rf /root/Friendify
-              git clone https://github.com/${{ github.repository }}.git /root/Friendify
-            fi
-
             cd /root/Friendify
-            curl -o compose.prod.yaml https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/compose.prod.yaml
+
+            git fetch --all
+            git reset --hard origin/${{ github.ref_name }}
+
+            test -f .env || (echo ".env missing" && exit 1)
 
             docker compose -f compose.prod.yaml up -d --build api --remove-orphans
             docker system prune -f
@@ -98,14 +96,12 @@ jobs:
           key: ${{ secrets.VPS_SSH_KEY }}
           script: |
             set -e
-
-            if [ ! -d "/root/Friendify/.git" ]; then
-              rm -rf /root/Friendify
-              git clone https://github.com/${{ github.repository }}.git /root/Friendify
-            fi
-
             cd /root/Friendify
-            curl -o compose.prod.yaml https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/compose.prod.yaml
+
+            git fetch --all
+            git reset --hard origin/${{ github.ref_name }}
+
+            test -f .env || (echo ".env missing" && exit 1)
 
             docker compose -f compose.prod.yaml up -d --build frontend --remove-orphans
             docker system prune -f
